version: '3.7'
#Create by Jesus Tejerina Rivera
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginxb
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    depends_on:
      - php
      - mariadb
    networks:
      - demo

  mariadb:
    image: mariadb:10.6
    container_name: mariadbb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=demo
      - MARIADB_DATABASE=demo
      - MARIADB_ROOT_PASSWORD=demo
      - MARIADB_SKIP_TEST_DB=yes
    ports:
      - 4306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - demo

  php:
    image: jesusitodocker/lrvl10:1.0
    container_name: phpb
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    ports:
      - 9000:80
    networks:
      - demo

  phpmyadmin:
    image: phpmyadmin:5.0
    container_name: phpmyadminb
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8090:80
    depends_on:
      - mariadb
    networks:
      - demo
     
networks:
  demo:
